# Generated by Django 4.1.5 on 2023-02-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_trip_day_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='finished',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
