# Generated by Django 4.1.5 on 2023-02-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_trip_finished_alter_trip_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='finished',
        ),
        migrations.AddField(
            model_name='trip',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
